apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: asia.gcr.io/eunoia0523/petclinic:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests: ## ì˜¤í† íŒŒì¼ëŸ¿ ëª¨ë“œì—ì„œ ì—†ìœ¼ë©´ ì—ëŸ¬ ë°œƒ 
            memory: "100Mi"
            cpu: "250m"
          limits: ## limitì´ ì—†ìœ¼ë©´ ì˜¤í† ìŠ¤ì¼€ì¼ë§ ë¬¸ì œ ë°œìƒ  
            cpu: "500m"
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
